plugin: gcp_compute
zones:
  - europe-west1-b
projects:
  - docker-267619
scopes:
  - https://www.googleapis.com/auth/compute
service_account_file: ~/Users/ruakbdg/.config/gcloud/application_default_credentials.json
auth_kind: serviceaccount
filters:
  - labels.env = stage
keyed_groups:
  # <prefix><separator><key>
  - prefix: ""
    separator: ""
    key: labels.ansible_group
hostnames:
  # List hosts by name instead of the default public ip
  - name
compose:
  # Set an inventory parameter to use the Public IP address to connect to the host
  # For Private ip use "networkInterfaces[0].networkIP"
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
